# Generated by Django 4.0.4 on 2022-07-13 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DoctorPay',
        ),
        migrations.DeleteModel(
            name='Ishlatilgan',
        ),
        migrations.DeleteModel(
            name='Kashlar',
        ),
    ]
