# Generated by Django 4.0.4 on 2022-07-19 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_cupon_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupon',
            name='checked',
            field=models.BooleanField(default=False),
        ),
    ]
